stages:
  - install
  - build-client
  - build-server
  - deploy

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - server/node_modules
    - client/node_modules
    - server/html
    - server/static

install_dep:
  stage: install
  script:
    - cd server
    - npm install
    - cd ../client
    - npm install
  tags:
    - aliyun1

build_client:
  stage: build-client
  script:
    - cd client
    - npm run build
    - mkdir -p ../server/html
    - rsync -av build/index.html ../server/html
    - cp build/favicon.ico ../server/html/
    - mkdir -p ../server/static
    - rsync -av build/static/* ../server/static
  tags:
    - aliyun1

build_server:
  stage: build-server
  script:
    - zip -r server.zip server
  tags:
    - aliyun1
  artifacts:
    paths:
      - server.zip
    expire_in: 1d

deploy-server:
  stage: deploy
  script:
    - echo "hello"
    - mkdir -p ~/deploy/graphql-mongdb-angular
    - unzip -o server.zip -d ~/deploy/graphql-mongdb-angular
    - mkdir -p ~/app/graphql-mongdb-angular 
    - rsync -av ~/deploy/graphql-mongdb-angular/* ~/app/graphql-mongdb-angular 
    - cd ~/app/graphql-mongdb-angular/server
    - pm2 stop graphql-mongodb-react || echo "graphql-mongodb-react is not exsit"
    - pm2 start app.js --name graphql-mongodb-react
  tags:
    - aliyun1