stages:
  - install
  - build-client
  - build-server
  - deploy

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - server/node_modules
    - client/node_modules
    - server/html
    - server/static

install_dep:
  stage: install
  script:
    - cd server
    - npm install
    - cd ../client
    - npm install
  tags:
    - aliyun1

build_client:
  stage: build-client
  script:
    - cd client
    - npm run build
    - rsync -av build/index.html ../server/html
    - cp build/favicon.ico ../server/html/favicon.ico
    - rsync -av build/static ../server/static
  tags:
    - aliyun1

build_server:
  stage: build-server
  script:
    - zip -rf server.zip server
  tags:
    - aliyun1
  artifacts:
    paths:
      - server.zip
    expire_in: 1d

deploy-server:
  stage: deploy
  script:
    - echo "hello"
  tags:
    - aliyun1